[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[[chains]]
id = "axelar-testnet-lisbon-3"
type = "CosmosSdk"
rpc_addr = "https://axelartest-rpc.quantnode.tech/"
grpc_addr = "http://axelartest-grpc.quantnode.tech:9090/"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "axelar"
key_name = "axelar"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false

[chains.event_source]
mode = "push"
url = "wss://axelartest-rpc.quantnode.tech/websocket"
batch_delay = "500ms"

[chains.trust_threshold]
numerator = "1"
denominator = "3"

[chains.gas_price]
price = 0.025
denom = "uaxl"

[chains.packet_filter]
policy = "deny"
list = []

[chains.packet_filter.min_fees]

[chains.address_type]
derivation = "cosmos"

[[chains]]
id = "agoriclocal"
type = "CosmosSdk"
rpc_addr = "http://127.0.0.1:26657/"
grpc_addr = "http://127.0.0.1:9090"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "agoric"
key_name = "rly1"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false

[chains.event_source]
mode = "push"
url = "ws://127.0.0.1:26657/websocket"
batch_delay = "500ms"

[chains.trust_threshold]
numerator = "1"
denominator = "3"

[chains.gas_price]
price = 0.025
denom = "ubld"

[chains.packet_filter]
policy = "deny"
list = []

[chains.packet_filter.min_fees]

[chains.address_type]
derivation = "cosmos"

